name: Deploy to Azure Function App

on:
  push:
    branches:
      - main  # or your desired deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # match your local dev version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy Azure Function App (Remote Build)
      uses: Azure/functions-action@v1
      with:
        app-name: VeeravnChatBotFunction            # 🔁 Replace with your Function App name
        package: '.'                                # Use the current directory as the deploy package
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true        # 🚀 Triggers remote build (installs requirements.txt)
